/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as DoctorsDoctorIdIndexRouteImport } from './routes/doctors.$doctorId.index'
import { Route as AuthenticatedReceiptsAppointmentIdRouteImport } from './routes/_authenticated/receipts.$appointmentId'
import { Route as AuthenticatedPaymentAppointmentIdRouteImport } from './routes/_authenticated/payment.$appointmentId'
import { Route as AuthenticatedBookingReviewRouteImport } from './routes/_authenticated/booking.review'
import { Route as AuthenticatedAppointmentsAppointmentIdRouteImport } from './routes/_authenticated/appointments.$appointmentId'
import { Route as ApiPublicPaymentsVerifyRouteImport } from './routes/api/public/payments.verify'
import { Route as ApiPublicPaymentsMarkFailedRouteImport } from './routes/api/public/payments.mark-failed'
import { Route as ApiPublicPaymentsCreateOrderRouteImport } from './routes/api/public/payments.create-order'
import { Route as AuthenticatedDoctorsDoctorIdBookRouteImport } from './routes/_authenticated/doctors.$doctorId.book'
import { Route as AuthenticatedAppointmentsAppointmentIdRescheduleRouteImport } from './routes/_authenticated/appointments.$appointmentId.reschedule'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DoctorsDoctorIdIndexRoute = DoctorsDoctorIdIndexRouteImport.update({
  id: '/doctors/$doctorId/',
  path: '/doctors/$doctorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceiptsAppointmentIdRoute =
  AuthenticatedReceiptsAppointmentIdRouteImport.update({
    id: '/receipts/$appointmentId',
    path: '/receipts/$appointmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentAppointmentIdRoute =
  AuthenticatedPaymentAppointmentIdRouteImport.update({
    id: '/payment/$appointmentId',
    path: '/payment/$appointmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingReviewRoute =
  AuthenticatedBookingReviewRouteImport.update({
    id: '/booking/review',
    path: '/booking/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsAppointmentIdRoute =
  AuthenticatedAppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsVerifyRoute = ApiPublicPaymentsVerifyRouteImport.update({
  id: '/api/public/payments/verify',
  path: '/api/public/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsMarkFailedRoute =
  ApiPublicPaymentsMarkFailedRouteImport.update({
    id: '/api/public/payments/mark-failed',
    path: '/api/public/payments/mark-failed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCreateOrderRoute =
  ApiPublicPaymentsCreateOrderRouteImport.update({
    id: '/api/public/payments/create-order',
    path: '/api/public/payments/create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDoctorsDoctorIdBookRoute =
  AuthenticatedDoctorsDoctorIdBookRouteImport.update({
    id: '/doctors/$doctorId/book',
    path: '/doctors/$doctorId/book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsAppointmentIdRescheduleRoute =
  AuthenticatedAppointmentsAppointmentIdRescheduleRouteImport.update({
    id: '/reschedule',
    path: '/reschedule',
    getParentRoute: () => AuthenticatedAppointmentsAppointmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/account': typeof AuthenticatedAccountRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRouteWithChildren
  '/booking/review': typeof AuthenticatedBookingReviewRoute
  '/payment/$appointmentId': typeof AuthenticatedPaymentAppointmentIdRoute
  '/receipts/$appointmentId': typeof AuthenticatedReceiptsAppointmentIdRoute
  '/doctors/$doctorId/': typeof DoctorsDoctorIdIndexRoute
  '/appointments/$appointmentId/reschedule': typeof AuthenticatedAppointmentsAppointmentIdRescheduleRoute
  '/doctors/$doctorId/book': typeof AuthenticatedDoctorsDoctorIdBookRoute
  '/api/public/payments/create-order': typeof ApiPublicPaymentsCreateOrderRoute
  '/api/public/payments/mark-failed': typeof ApiPublicPaymentsMarkFailedRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/account': typeof AuthenticatedAccountRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/doctors': typeof DoctorsIndexRoute
  '/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRouteWithChildren
  '/booking/review': typeof AuthenticatedBookingReviewRoute
  '/payment/$appointmentId': typeof AuthenticatedPaymentAppointmentIdRoute
  '/receipts/$appointmentId': typeof AuthenticatedReceiptsAppointmentIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdIndexRoute
  '/appointments/$appointmentId/reschedule': typeof AuthenticatedAppointmentsAppointmentIdRescheduleRoute
  '/doctors/$doctorId/book': typeof AuthenticatedDoctorsDoctorIdBookRoute
  '/api/public/payments/create-order': typeof ApiPublicPaymentsCreateOrderRoute
  '/api/public/payments/mark-failed': typeof ApiPublicPaymentsMarkFailedRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/doctors/': typeof DoctorsIndexRoute
  '/_authenticated/appointments/$appointmentId': typeof AuthenticatedAppointmentsAppointmentIdRouteWithChildren
  '/_authenticated/booking/review': typeof AuthenticatedBookingReviewRoute
  '/_authenticated/payment/$appointmentId': typeof AuthenticatedPaymentAppointmentIdRoute
  '/_authenticated/receipts/$appointmentId': typeof AuthenticatedReceiptsAppointmentIdRoute
  '/doctors/$doctorId/': typeof DoctorsDoctorIdIndexRoute
  '/_authenticated/appointments/$appointmentId/reschedule': typeof AuthenticatedAppointmentsAppointmentIdRescheduleRoute
  '/_authenticated/doctors/$doctorId/book': typeof AuthenticatedDoctorsDoctorIdBookRoute
  '/api/public/payments/create-order': typeof ApiPublicPaymentsCreateOrderRoute
  '/api/public/payments/mark-failed': typeof ApiPublicPaymentsMarkFailedRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/account'
    | '/payments'
    | '/visits'
    | '/doctors/'
    | '/appointments/$appointmentId'
    | '/booking/review'
    | '/payment/$appointmentId'
    | '/receipts/$appointmentId'
    | '/doctors/$doctorId/'
    | '/appointments/$appointmentId/reschedule'
    | '/doctors/$doctorId/book'
    | '/api/public/payments/create-order'
    | '/api/public/payments/mark-failed'
    | '/api/public/payments/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/account'
    | '/payments'
    | '/visits'
    | '/doctors'
    | '/appointments/$appointmentId'
    | '/booking/review'
    | '/payment/$appointmentId'
    | '/receipts/$appointmentId'
    | '/doctors/$doctorId'
    | '/appointments/$appointmentId/reschedule'
    | '/doctors/$doctorId/book'
    | '/api/public/payments/create-order'
    | '/api/public/payments/mark-failed'
    | '/api/public/payments/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how-it-works'
    | '/_authenticated/account'
    | '/_authenticated/payments'
    | '/_authenticated/visits'
    | '/doctors/'
    | '/_authenticated/appointments/$appointmentId'
    | '/_authenticated/booking/review'
    | '/_authenticated/payment/$appointmentId'
    | '/_authenticated/receipts/$appointmentId'
    | '/doctors/$doctorId/'
    | '/_authenticated/appointments/$appointmentId/reschedule'
    | '/_authenticated/doctors/$doctorId/book'
    | '/api/public/payments/create-order'
    | '/api/public/payments/mark-failed'
    | '/api/public/payments/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
  DoctorsDoctorIdIndexRoute: typeof DoctorsDoctorIdIndexRoute
  ApiPublicPaymentsCreateOrderRoute: typeof ApiPublicPaymentsCreateOrderRoute
  ApiPublicPaymentsMarkFailedRoute: typeof ApiPublicPaymentsMarkFailedRoute
  ApiPublicPaymentsVerifyRoute: typeof ApiPublicPaymentsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/doctors/$doctorId/': {
      id: '/doctors/$doctorId/'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId/'
      preLoaderRoute: typeof DoctorsDoctorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/receipts/$appointmentId': {
      id: '/_authenticated/receipts/$appointmentId'
      path: '/receipts/$appointmentId'
      fullPath: '/receipts/$appointmentId'
      preLoaderRoute: typeof AuthenticatedReceiptsAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/$appointmentId': {
      id: '/_authenticated/payment/$appointmentId'
      path: '/payment/$appointmentId'
      fullPath: '/payment/$appointmentId'
      preLoaderRoute: typeof AuthenticatedPaymentAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/review': {
      id: '/_authenticated/booking/review'
      path: '/booking/review'
      fullPath: '/booking/review'
      preLoaderRoute: typeof AuthenticatedBookingReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/$appointmentId': {
      id: '/_authenticated/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AuthenticatedAppointmentsAppointmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/verify': {
      id: '/api/public/payments/verify'
      path: '/api/public/payments/verify'
      fullPath: '/api/public/payments/verify'
      preLoaderRoute: typeof ApiPublicPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mark-failed': {
      id: '/api/public/payments/mark-failed'
      path: '/api/public/payments/mark-failed'
      fullPath: '/api/public/payments/mark-failed'
      preLoaderRoute: typeof ApiPublicPaymentsMarkFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/create-order': {
      id: '/api/public/payments/create-order'
      path: '/api/public/payments/create-order'
      fullPath: '/api/public/payments/create-order'
      preLoaderRoute: typeof ApiPublicPaymentsCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/doctors/$doctorId/book': {
      id: '/_authenticated/doctors/$doctorId/book'
      path: '/doctors/$doctorId/book'
      fullPath: '/doctors/$doctorId/book'
      preLoaderRoute: typeof AuthenticatedDoctorsDoctorIdBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/$appointmentId/reschedule': {
      id: '/_authenticated/appointments/$appointmentId/reschedule'
      path: '/reschedule'
      fullPath: '/appointments/$appointmentId/reschedule'
      preLoaderRoute: typeof AuthenticatedAppointmentsAppointmentIdRescheduleRouteImport
      parentRoute: typeof AuthenticatedAppointmentsAppointmentIdRoute
    }
  }
}

interface AuthenticatedAppointmentsAppointmentIdRouteChildren {
  AuthenticatedAppointmentsAppointmentIdRescheduleRoute: typeof AuthenticatedAppointmentsAppointmentIdRescheduleRoute
}

const AuthenticatedAppointmentsAppointmentIdRouteChildren: AuthenticatedAppointmentsAppointmentIdRouteChildren =
  {
    AuthenticatedAppointmentsAppointmentIdRescheduleRoute:
      AuthenticatedAppointmentsAppointmentIdRescheduleRoute,
  }

const AuthenticatedAppointmentsAppointmentIdRouteWithChildren =
  AuthenticatedAppointmentsAppointmentIdRoute._addFileChildren(
    AuthenticatedAppointmentsAppointmentIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedAppointmentsAppointmentIdRoute: typeof AuthenticatedAppointmentsAppointmentIdRouteWithChildren
  AuthenticatedBookingReviewRoute: typeof AuthenticatedBookingReviewRoute
  AuthenticatedPaymentAppointmentIdRoute: typeof AuthenticatedPaymentAppointmentIdRoute
  AuthenticatedReceiptsAppointmentIdRoute: typeof AuthenticatedReceiptsAppointmentIdRoute
  AuthenticatedDoctorsDoctorIdBookRoute: typeof AuthenticatedDoctorsDoctorIdBookRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedAppointmentsAppointmentIdRoute:
    AuthenticatedAppointmentsAppointmentIdRouteWithChildren,
  AuthenticatedBookingReviewRoute: AuthenticatedBookingReviewRoute,
  AuthenticatedPaymentAppointmentIdRoute:
    AuthenticatedPaymentAppointmentIdRoute,
  AuthenticatedReceiptsAppointmentIdRoute:
    AuthenticatedReceiptsAppointmentIdRoute,
  AuthenticatedDoctorsDoctorIdBookRoute: AuthenticatedDoctorsDoctorIdBookRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
  DoctorsDoctorIdIndexRoute: DoctorsDoctorIdIndexRoute,
  ApiPublicPaymentsCreateOrderRoute: ApiPublicPaymentsCreateOrderRoute,
  ApiPublicPaymentsMarkFailedRoute: ApiPublicPaymentsMarkFailedRoute,
  ApiPublicPaymentsVerifyRoute: ApiPublicPaymentsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
